### ISSUE TITLE
Code review Devgym 🎉 

### ISSUE THREAD

**Issue by filhodanuvem** [ropehapi/encurtador-url-go#4]
Parabéns @ropehapi por ter completado esse desafio da Devgym 🎉 . Me chamou a atenção a simplicidade no seu código, e isso é uma coisa ótima principalmente na comunidade Go. Alguns pontos a se atentar na solução, na minha opinião:

* [Concatenar parâmetros que vem de uma url direto pra uma consulta sql](https://github.com/ropehapi/encurtador-url-go/blob/main/main.go#L61) acaba sendo uma brecha de segurança pra um tipo de ataque SQL injection. Acho que se voce usar [qualquer função](https://pkg.go.dev/database/sql#DB.QueryContext) do pacote sql que recebe parametros indivualmente ja vai ter um nivel de segurança maior. 
* Seria legal que a API retornasse 404 quando um código não é encontrado. [Afinal os status codes 5xx](https://pkg.go.dev/database/sql#DB.QueryContext) são usados quando há um problema do lado do servidor, mas nesse caso o usuário está pedindo algo que não existe.  
* Gostei que você documentou como rodar o projeto, acho que seria legal usar variáveis de ambientes e a função [os.Getenv](https://gobyexample.com/environment-variables) para as pessoas especificarem facilmente suas credencias de banco de dados. Assim elas não precisam [editar o código antes de rodar](https://github.com/ropehapi/encurtador-url-go/blob/main/config/database.go#L10). Caso nenhuma env var seja especificada, voce pode manter os valores padrão. 

Se quiser continuar praticando com o projeto aqui vão algumas ideias 💡 : 
* Estudar docker e docker-compose para tornar o projeto ainda mais portável. 
* Pensar em soluçoes de como expirar urls curtas muito antigas para liberar novos códigos/chaves.
* Contador de click em url curta.

**Comment by ropehapi** [comment]
Olá @filhodanuvem, muito obrigado pelo feedback, acredito que code reviews eficientes sejam a melhor maneira de ensinar e aprender sobre escrita de código. 

Com toda a certeza corrigirei e passarei a me atentar sobre os três pontos que você levantou e subirei um commit contendo as alterações para fechar o projeto.

**Comment by ropehapi** [comment]
Bom dia/tarde/noite, @filhodanuvem!!!

Primeiramente, gostaria de me desculpar pela demora para aplicar as três melhorias por você mencionadas durante sua correção, tendo em vista que nos últimos meses decidi me aprofundar mais nos estudos de Golang antes de continuar com os desafios da DevGym.

Durante a semana passada, subi o último commit do desafio de modo a ter como feitas todas as três melhorias apontadas por vc. Dado isso, darei a Issue como fechada. 

Muito obrigado pelo feedback e até o próximo desafio, que será a API de transferência de dinheiro (Inclusive, link para o repositório aqui: https://github.com/ropehapi/api-transferencia-dinheiro-go).

**Comment by filhodanuvem** [comment]
Nice! Escolheu bem esse segundo desafio, bons estudos!
